services:
  db:
    container_name: postgres_chamasoft
    image: postgres:15.2
    environment:
      POSTGRES_USER: chamasoft
      POSTGRES_PASSWORD: password
      PGDATA: \data\postgres
    volumes:
      - postgres:\data\postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  chamasofttest-api:
    container_name: chamasoft_test-api
    image: fredodhis/chamasoft_test-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
